package com.nutribalance.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.core.graphics.toColorInt

val positiveBalanceLight = Color("#43A047".toColorInt())
val positiveBalanceDark = Color("#76FF03".toColorInt())

val primaryLight = Color(0xFF003AC3)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3B62EE)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF4D5B96)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBBC6FF)
val onSecondaryContainerLight = Color(0xFF26346C)
val tertiaryLight = Color(0xFF7C0F96)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA641BE)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B23)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B23)
val surfaceVariantLight = Color(0xFFE0E1F4)
val onSurfaceVariantLight = Color(0xFF444655)
val outlineLight = Color(0xFF747686)
val outlineVariantLight = Color(0xFFC4C5D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3039)
val inverseOnSurfaceLight = Color(0xFFF0EFFC)
val inversePrimaryLight = Color(0xFFB8C4FF)

val primaryDark = Color(0xFFB8C4FF)
val onPrimaryDark = Color(0xFF002485)
val primaryContainerDark = Color(0xFF1747D5)
val onPrimaryContainerDark = Color(0xFFFEFBFF)
val secondaryDark = Color(0xFFB8C4FF)
val onSecondaryDark = Color(0xFF1E2C64)
val secondaryContainerDark = Color(0xFF2B3971)
val onSecondaryContainerDark = Color(0xFFC5CEFF)
val tertiaryDark = Color(0xFFF4AEFF)
val onTertiaryDark = Color(0xFF56006A)
val tertiaryContainerDark = Color(0xFF8B25A4)
val onTertiaryContainerDark = Color(0xFFFFFBFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11131B)
val onBackgroundDark = Color(0xFFE2E1ED)
val surfaceDark = Color(0xFF11131B)
val onSurfaceDark = Color(0xFFE2E1ED)
val surfaceVariantDark = Color(0xFF444655)
val onSurfaceVariantDark = Color(0xFFC4C5D7)
val outlineDark = Color(0xFF8E90A1)
val outlineVariantDark = Color(0xFF444655)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E1ED)
val inverseOnSurfaceDark = Color(0xFF2F3039)
val inversePrimaryDark = Color(0xFF254FDD)
